# Generated by Django 5.1.2 on 2026-04-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobresult",
            name="matched_hard_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="matched_soft_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="weak_skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
