# Generated by Django 5.1.2 on 2026-04-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_jobresult_matched_hard_skills_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobresult",
            old_name="ats_score",
            new_name="overall_score",
        ),
        migrations.RenameField(
            model_name="jobresult",
            old_name="matched_hard_skills",
            new_name="recruiter_tips",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="contact_info_score",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="education_score",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="eligibility_score",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="experience_score",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="improvement_suggestion",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="matched_soft_skills",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="matching_reason",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="skills_score",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="structure_score",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="tone_score",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="weak_skills",
        ),
        migrations.AddField(
            model_name="jobresult",
            name="details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="score_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="searchability",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
