# Generated by Django 5.1.2 on 2026-03-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "resumes",
            "0002_resume_certifications_resume_education_resume_email_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="certifications",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="education",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="email",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="name",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="portfolio",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="skills",
        ),
    ]
