# Generated by Django 5.1.2 on 2026-04-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resumes",
            "0003_remove_resume_certifications_remove_resume_education_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="pipeline_status",
            field=models.CharField(
                choices=[
                    ("IDLE", "Idle"),
                    ("RECOMPUTING", "Recomputing Pipeline"),
                    ("COMPLETED", "Completed Pipeline"),
                    ("ERROR", "Pipeline Error"),
                ],
                default="IDLE",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="resume_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash of parsed_data to detect changes",
                max_length=64,
                null=True,
            ),
        ),
    ]
