# Generated by Django 5.1.2 on 2026-04-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0004_resume_pipeline_status_resume_resume_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="locked_jd",
            field=models.TextField(
                blank=True,
                help_text="The Auto-Generated Market Job Description",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="locked_target_role",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
