# Generated by Django 5.1.2 on 2026-04-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0005_resume_locked_jd_resume_locked_target_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="ats_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resume",
            name="ats_score_overall",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="cv_variants",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="resume",
            name="skill_gap_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
