# Generated by Django 5.1.2 on 2026-04-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0006_resume_ats_completed_resume_ats_score_overall_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="vector_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
