# Generated by Django 5.1.2 on 2026-04-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0007_resume_vector_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="vector_embedding",
            field=models.JSONField(
                blank=True,
                help_text="Sentence-BERT embedding for semantic search",
                null=True,
            ),
        ),
    ]
