# Generated by Django 5.1.2 on 2026-04-19 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("job_seeker", "Job Seeker"),
                            ("hr", "HR / Recruiter"),
                        ],
                        default="job_seeker",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "last_degree",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_degree",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "student_or_graduate",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "field_of_study",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("university", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("company_address", models.TextField(blank=True, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("has_completed_onboarding", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CareerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "graduation_year",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("cgpa", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "career_level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("experience", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "target_job_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("preferred_job_type", models.JSONField(blank=True, default=list)),
                ("preferred_locations", models.JSONField(blank=True, default=list)),
                ("interested_industries", models.JSONField(blank=True, default=list)),
                (
                    "linkedin_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "portfolio_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("skills", models.JSONField(blank=True, default=list)),
                ("experience_list", models.JSONField(blank=True, default=list)),
                ("projects", models.JSONField(blank=True, default=list)),
                ("education_list", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
