# Generated by Django 5.1.2 on 2026-04-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerprofile",
            name="is_searchable",
            field=models.BooleanField(
                default=True, help_text="Allow HR to discover this profile"
            ),
        ),
        migrations.AddField(
            model_name="careerprofile",
            name="vector_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
