# Generated by Django 5.1.2 on 2026-04-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_careerprofile_is_searchable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careerprofile",
            name="is_searchable",
            field=models.BooleanField(
                default=True, help_text="Allow HR/Recruiters to find this profile"
            ),
        ),
        migrations.AlterField(
            model_name="careerprofile",
            name="vector_embedding",
            field=models.JSONField(
                blank=True, help_text="Semantic vector for quick matching", null=True
            ),
        ),
    ]
