# Generated by Django 5.1.2 on 2026-04-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_job_search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobresult",
            name="is_saved",
            field=models.BooleanField(default=False),
        ),
    ]
